Fixes issue #132
anuvu/zot pull request #135
Opened 2020-09-04 23:26 UTC by shimish2

If image does not have any fixed tags, empty list with no error should be returned

2020-09-08 19:07 UTC, rchincha submitted a review, later dismissed
lgtm

2020-09-08 19:10 UTC, tsnaik requested changes

2020-09-08 23:17 UTC, tsnaik approved these changes
looks good

2020-09-09 14:39 UTC, tsnaik approved these changes

2020-09-10 17:49 UTC, rchincha approved these changes
lgtm

2020-09-10 17:49 UTC, merged